name: mobile_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #architecture
  flutter_bloc: ^0.21.0
  bloc: ^0.15.0
  dio: ^3.0.2
  retry: ^3.0.0+1
  cached_network_image: ^1.1.1
  video_player:
    git:
      url: https://github.com/tapkain/plugins.git
      path: packages/video_player
  flutter_sound: ^1.4.3
  audioplayers: ^0.13.2
  alice: ^0.0.14
  transparent_image: ^1.0.0
  fl_chart: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  dio: ^3.0.2


flutter:
  uses-material-design: true

